language: cpp
os:
  - osx
  - linux

env:
  - LLVM_BUILD_TYPE=Release
  - LLVM_BUILD_TYPE=Debug

install: true
script:
  - cmake . -DLLVM_BUILD_TYPE="${LLVM_BUILD_TYPE}"
  - make -j3 check

notifications:
  email:
    recipients:
      - "dagger@repzret.org"
