language: cpp
os:
  - osx
  - linux

before_install: if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew upgrade cmake; else sudo add-apt-repository --yes ppa:kalakris/cmake && sudo apt-get update -qq && sudo apt-get install cmake; fi

env:
  - LLVM_BUILD_TYPE=Release
  - LLVM_BUILD_TYPE=Debug

install: true
script:
  - mkdir build && cd build
  - cmake .. -DLLVM_BUILD_TYPE="${LLVM_BUILD_TYPE}"
  - make -j3 check

notifications:
  email:
    recipients:
      - "dagger@repzret.org"
