language: cpp
os:
  - osx
  - linux

compiler:
  - clang
  - gcc

matrix:
  exclude:
    - os: osx
      compiler: gcc

install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew upgrade cmake; fi
  - if [ $TRAVIS_OS_NAME != osx ]; then sudo add-apt-repository --yes ppa:george-edison55/precise-backports; fi
  - if [ $TRAVIS_OS_NAME != osx ]; then sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test; fi
  - if [ $TRAVIS_OS_NAME != osx ]; then sudo apt-get update -qq; fi
  - if [ $TRAVIS_OS_NAME != osx ]; then sudo apt-get install cmake-data cmake g++-4.7; fi

env:
  - CMAKE_BUILD_TYPE=Release
  - CMAKE_BUILD_TYPE=Debug

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}"
  - make -j3 check

notifications:
  email:
    recipients:
      - "dagger@repzret.org"
